In [1]:
import numpy as np

# create numpy Array

In [2]:
arr=np.array([1,2,3,4,5,6])            # 1d array
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
print(arr)

[1 2 3 4 5 6]


In [5]:
type(arr)

numpy.ndarray

In [7]:
arr2=np.array([[1 , 2 , 3 , 4],[ 5 , 6 , 7 , 8]])       # 2d array
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr3=np.array([[ 2, 3 , 5,6],[4, 5, 6, 7],[24,71, 56,45],[45,76,82,35]])          # 3d array    
arr3                                                                              # tensor    

array([[ 2,  3,  5,  6],
       [ 4,  5,  6,  7],
       [24, 71, 56, 45],
       [45, 76, 82, 35]])

# dtype

In [11]:
np.array([1,2,3,4],dtype=int)

array([1, 2, 3, 4])

In [12]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [13]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [14]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

# arange

In [16]:
np.arange(1,13)          # it works as range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
np.arange(1,14,2)      #  1-13 , step 2

array([ 1,  3,  5,  7,  9, 11, 13])

# reshape

In [18]:
np.arange(1,13).reshape(2,6)          # 2 rows, 6 column

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
np.arange(1,13).reshape(6,2)          # 6 rows, 2 column

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [20]:
np.arange(1,13).reshape(3,4)          # 3 rows, 4 column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ones & zeros

In [21]:
np.ones((3,4))           # bydefault in float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
np.zeros((6,3))        # bydefault in float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.zeros((6,3),dtype=int)   

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# random,randomint  -   value range betn 0-1

In [27]:
np.random.rand(4)         # bydefault in float

array([0.49030379, 0.65090594, 0.55704383, 0.72085301])

In [28]:
np.random.randint(1,14)       # randon no.

10

In [29]:
np.random.randint(1,14,5)          #, random  1-13 , 5 no.

array([ 3,  7, 11, 10,  4], dtype=int32)

# linspace  - same difference of gap in each value

In [31]:
np.linspace(1,13,4)

array([ 1.,  5.,  9., 13.])

In [33]:
np.linspace(-2,13,3)

array([-2. ,  5.5, 13. ])

# identity

In [34]:
np.identity(4)   # diagonal elem 1 , remaining  value 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.identity(3)        # 3 * 3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attributes

In [37]:
a1=np.arange(7)       # 1d
a1

array([0, 1, 2, 3, 4, 5, 6])

In [40]:
a2=np.arange(20,dtype=float).reshape(4,5)
a2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [41]:
a3=np.arange(27,dtype=float).reshape(3,3,3)   # 3d tensor
a3

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

# ndim    (n dimension)

In [42]:
a1.ndim

1

In [43]:
a2.ndim

2

In [44]:
a3.ndim

3

# shape

In [45]:
a1.shape

(7,)

In [46]:
a2.shape

(4, 5)

In [47]:
a3.shape

(3, 3, 3)

# size   -  total elem

In [49]:
a3

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [50]:
a3.size

27

In [51]:
a2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [52]:
a2.size

20

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6])

In [54]:
a1.size

7

# itemsize - result in bytes

# 64 bits = 8 bytes

In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
a1.itemsize            #int64

8

In [57]:
a2          

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [59]:
a2.itemsize          # float64

8

In [60]:
a3

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [61]:
a3.itemsize          # float64

8

# dtype

In [62]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
float64


# changing datatype - astype()

In [63]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [64]:
a.astype(float)

array([0., 1., 2., 3., 4., 5., 6.])

# array operation

In [66]:
x1=np.arange(1,13).reshape(3,4)
x2=np.arange(12,24).reshape(4,3)

In [67]:
x1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
x2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

# scalar operations

# arithmatic operators

In [69]:
x1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
x1 + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [71]:
x1 - 2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [72]:
x1 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [73]:
x1 ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [74]:
x1 % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [75]:
x1 // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

# relational operators

In [77]:
x2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [79]:
x2 < 20

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [80]:
x2 >= 15

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# vector operations

In [81]:
x1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
x2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [84]:
x1 + x2        # shape must be same

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [88]:
z1=np.arange(1,11).reshape(2,5)
z1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [89]:
z2=np.arange(11,21).reshape(2,5)
z2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [90]:
z1 + z2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [91]:
z1 - z2

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [92]:
z1 * z2

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [93]:
z1 / z2

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

In [94]:
z1//z2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [95]:
z1%z2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# array function

In [96]:
k1 = np.random.random((3,3)) 
k1

array([[0.51405708, 0.98088702, 0.90910516],
       [0.15431119, 0.88803197, 0.23695835],
       [0.98722035, 0.20482784, 0.56044665]])

In [97]:
k1 = np.round(k1*100)      
k1

array([[51., 98., 91.],
       [15., 89., 24.],
       [99., 20., 56.]])

In [98]:
np.max(k1)

np.float64(99.0)

In [99]:
np.min(k1)

np.float64(15.0)

In [100]:
np.sum(k1)

np.float64(543.0)

In [101]:
np.prod(k1)

np.float64(1615784243673600.0)

# axis = 0 - column
# axis = 1 - row

In [105]:
k1

array([[51., 98., 91.],
       [15., 89., 24.],
       [99., 20., 56.]])

In [106]:
np.max(k1,axis = 0)

array([99., 98., 91.])

In [108]:
np.max(k1,axis = 1)

array([98., 89., 99.])

In [109]:
np.min(k1,axis = 0)

array([15., 20., 24.])

In [111]:
np.min(k1,axis = 1)

array([51., 15., 20.])

In [112]:
np.sum(k1,axis = 0)

array([165., 207., 171.])

In [113]:
np.sum(k1,axis = 1)

array([240., 128., 175.])

In [114]:
np.prod(k1,axis = 0)

array([ 75735., 174440., 122304.])

In [115]:
np.prod(k1,axis = 1)

array([454818.,  32040., 110880.])

# statitics related functions

# mean

In [116]:
k1

array([[51., 98., 91.],
       [15., 89., 24.],
       [99., 20., 56.]])

In [117]:
np.mean(k1)

np.float64(60.333333333333336)

In [118]:
np.mean(k1,axis=0)

array([55., 69., 57.])

In [119]:
np.mean(k1,axis=1)

array([80.        , 42.66666667, 58.33333333])

# median

In [120]:
k1

array([[51., 98., 91.],
       [15., 89., 24.],
       [99., 20., 56.]])

In [121]:
np.median(k1,axis=0)

array([51., 89., 56.])

In [122]:
np.median(k1,axis=1)

array([91., 24., 56.])

# variance

In [124]:
np.var(k1,axis=0)

array([1184.        , 1214.        ,  748.66666667])

In [125]:
np.var(k1,axis=1)

array([ 428.66666667, 1086.88888889, 1042.88888889])

# dot product

In [131]:
t1=np.arange(1,11).reshape(2,5)
t2=np.arange(11,21).reshape(5,2)

In [132]:
print(t1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [133]:
print(t2)

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [134]:
np.dot(t1,t2)     # mult of row and column

array([[245, 260],
       [620, 660]])

# round,floor,ceil

In [139]:
f1=np.array([1.3421312 , 2.76834927 ,3.6492888 , 4.437923810 , 5.89013810,])

In [140]:
np.round(f1,decimals=2)

array([1.34, 2.77, 3.65, 4.44, 5.89])

In [141]:
np.floor(f1)      # approx lower value

array([1., 2., 3., 4., 5.])

In [142]:
np.ceil(f1)      #  approx upper value

array([2., 3., 4., 5., 6.])

# indexing and slicing

In [167]:
j1=np.arange(4,10)
j2=np.arange(1,7).reshape(2,3)
j3=np.arange(27).reshape(3,3,3)

In [168]:
j1


array([4, 5, 6, 7, 8, 9])

In [169]:
j2


array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
j3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
j3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [172]:
j1                  # 1d

array([4, 5, 6, 7, 8, 9])

In [175]:
print(j1[2])

6


In [176]:
print(j1[-2])

8


In [177]:
j2                   # 2d

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
print(j2[0,1])

2


In [181]:
print(j2[0,2])

3


In [182]:
j3          # 3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [183]:
print(j3[2,1,2])        # 3rd block,2nd row,3rd col

23


In [184]:
print(j3[1,0,1])

10


In [185]:
print(j3[0,0,1])

1


In [186]:
print(j3[0,0,0])

0


# slicing

# slicing on 1d

In [187]:
j1

array([4, 5, 6, 7, 8, 9])

In [189]:
print(j1[1:4])

[5 6 7]


In [191]:
print(j1[0:-4])

[4 5]


In [192]:
print(j1[:])

[4 5 6 7 8 9]


# slicing on 2d

In [193]:
j2

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
print(j2[1:4])

[[4 5 6]]


In [197]:
print(j2[0:, -3:])

[[1 2 3]
 [4 5 6]]


In [210]:
print(j2[1:3,-4: : ])

[[4 5 6]]


# slicing on 3d

In [199]:
j3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [202]:
print(j3[0:2 , 1:3 ,1:3])

[[[ 4  5]
  [ 7  8]]

 [[13 14]
  [16 17]]]


In [206]:
print(j3[1:3 , 1:5 ,-5:-2])

[[[12]
  [15]]

 [[21]
  [24]]]


In [208]:
print(j3[1:3 , 1:5 ,: :-2])

[[[14 12]
  [17 15]]

 [[23 21]
  [26 24]]]


In [209]:
print(j3[1:3 , 1: : 2 ,: :-2])

[[[14 12]]

 [[23 21]]]


# iterating

# looping array in 1d

In [211]:
j1

array([4, 5, 6, 7, 8, 9])

In [212]:
for i in j1:
    print(i)

4
5
6
7
8
9


# looping array in 2d

In [213]:
j2

array([[1, 2, 3],
       [4, 5, 6]])

In [215]:
for i in j2:
    print(i)

[1 2 3]
[4 5 6]


# looping array in 3d

In [216]:
j3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [217]:
for i in j3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [218]:
for i in np.nditer(j3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# transpose

In [219]:
j1

array([4, 5, 6, 7, 8, 9])

In [220]:
np.transpose(j1)       # 1d transpose not possible bcoz there is no col and rows

array([4, 5, 6, 7, 8, 9])

In [221]:
j2

array([[1, 2, 3],
       [4, 5, 6]])

In [222]:
np.transpose(j2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [223]:
j3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [224]:
np.transpose(j3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [225]:
j2

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
j2.T        # 2d

array([[1, 4],
       [2, 5],
       [3, 6]])

In [227]:
j3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [228]:
j3.T      # 3d

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# ravel

In [229]:
# convert any dimension to 1d

In [230]:
j2

array([[1, 2, 3],
       [4, 5, 6]])

In [232]:
j2.ravel()

array([1, 2, 3, 4, 5, 6])

In [233]:
j3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [234]:
j3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [235]:
# stacking - dimension must be same

In [237]:
w1=np.arange(0,12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4)

In [238]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [239]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [241]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [242]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [246]:
# splitting - opposite of stacking    

In [247]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [248]:
np.hsplit(w1,2)             # split in 2 blocks

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [249]:
np.vsplit(w1,3)       # split in 3 blocks 

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [250]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [251]:
np.hsplit(w2,4)

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [254]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# advanced indexing and slicing

In [255]:
w=np.arange(12).reshape(3,4)
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [259]:
print(w[1,3] )          # 1th row , 3rd col

7


In [260]:
w[1:4]            # 1th row to 3rd row slicing

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [257]:
w[0:5]         # 0th row  to 4th row slicing

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [262]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [263]:
w[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

# fancy indexing

In [264]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# row

In [266]:
w[[0,2]]        # 0 , 2   row

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [267]:
w[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [268]:
w[[0,1,2]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# column

In [269]:
b=np.arange(0,24).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [271]:
b[[0,2,3]]         # row

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [274]:
b[ :, [1,3,4]]       #  1th , 3rd , 4th column

array([[ 1,  3,  4],
       [ 7,  9, 10],
       [13, 15, 16],
       [19, 21, 22]])

In [275]:
b[ :,[2,4]]

array([[ 2,  4],
       [ 8, 10],
       [14, 16],
       [20, 22]])

# Boolean indexing

In [283]:
G=np.random.randint(0,125,24).reshape(6,4)
G

array([[  8,  32,  85,  19],
       [ 92, 108,  26,  93],
       [  8,  29,  84, 123],
       [ 18,  53,   0,  52],
       [ 95,  99,  25,  16],
       [ 30,  53, 103,   5]], dtype=int32)

In [284]:
G>50

array([[False, False,  True, False],
       [ True,  True, False,  True],
       [False, False,  True,  True],
       [False,  True, False,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [285]:
G[G>=30]

array([ 32,  85,  92, 108,  93,  84, 123,  53,  52,  95,  99,  30,  53,
       103], dtype=int32)

In [286]:
G%3

array([[2, 2, 1, 1],
       [2, 0, 2, 0],
       [2, 2, 0, 0],
       [0, 2, 0, 1],
       [2, 0, 1, 1],
       [0, 2, 1, 2]], dtype=int32)

In [288]:
G[G%3==0]

array([108,  93,  84, 123,  18,   0,  99,  30], dtype=int32)

In [289]:
G [(G > 50 ) & (G % 2 == 0)] 


array([ 92, 108,  84,  52], dtype=int32)

# Broadcasting

# same shape

# diff shape

In [295]:
a=np.arange(0,6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b) 

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


# np.sort()

In [296]:
a= np.random.randint(1,100,15)  # 1d # 1-99 random 15 no.
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [297]:
b=np.random.randint(1,100,18).reshape(3,6)
b

array([[20, 55, 31, 24, 14, 49],
       [75, 33, 10, 92, 53, 62],
       [85, 41, 48, 42, 46, 83]], dtype=int32)

In [298]:
np.sort(a)

array([ 8,  9, 10, 14, 23, 26, 40, 42, 43, 52, 61, 62, 65, 78, 90],
      dtype=int32)

In [299]:
np.sort(a)[::-1]

array([90, 78, 65, 62, 61, 52, 43, 42, 40, 26, 23, 14, 10,  9,  8],
      dtype=int32)

In [300]:
b

array([[20, 55, 31, 24, 14, 49],
       [75, 33, 10, 92, 53, 62],
       [85, 41, 48, 42, 46, 83]], dtype=int32)

In [301]:
np.sort(b,axis=1)    # row wise

array([[14, 20, 24, 31, 49, 55],
       [10, 33, 53, 62, 75, 92],
       [41, 42, 46, 48, 83, 85]], dtype=int32)

In [303]:
b

array([[20, 55, 31, 24, 14, 49],
       [75, 33, 10, 92, 53, 62],
       [85, 41, 48, 42, 46, 83]], dtype=int32)

In [304]:
np.sort(b,axis=0)       # column wise

array([[20, 33, 10, 24, 14, 49],
       [75, 41, 31, 42, 46, 62],
       [85, 55, 48, 92, 53, 83]], dtype=int32)

# np.where

In [305]:
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [307]:
np.where(a>15)

(array([ 0,  2,  3,  4,  6,  7,  9, 10, 11, 13, 14]),)

In [308]:
np.where(a>30,0,a)         # >30 replace with  0

array([ 0, 10, 26,  0,  0,  9, 23,  0, 14,  0,  0,  0,  8,  0,  0],
      dtype=int32)

In [310]:
np.where(a>50,5,a)

array([ 5, 10, 26,  5,  5,  9, 23, 43, 14,  5,  5,  5,  8, 42, 40],
      dtype=int32)

# np.argmax , argmin

In [311]:
a        # 1d

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [313]:
print(np.argmax (a))


0


In [319]:
print(np.argmin (a) )    # 8 is on 12th index no.


12


In [320]:
b                 # 2d

array([[20, 55, 31, 24, 14, 49],
       [75, 33, 10, 92, 53, 62],
       [85, 41, 48, 42, 46, 83]], dtype=int32)

In [322]:
np.argmax (b,axis=0)       # each  col ,highest no. index position

array([2, 0, 2, 1, 1, 2])

In [323]:
np.argmax (b,axis=1)           # each row ,highest no. index position


array([1, 3, 0])

# np.cumsum 


In [324]:
# adding  current value with next value

In [325]:
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [326]:
np.cumsum (a)


array([ 90, 100, 126, 187, 265, 274, 297, 340, 354, 416, 481, 533, 541,
       583, 623])

In [327]:
b

array([[20, 55, 31, 24, 14, 49],
       [75, 33, 10, 92, 53, 62],
       [85, 41, 48, 42, 46, 83]], dtype=int32)

In [328]:
np.cumsum (b)


array([ 20,  75, 106, 130, 144, 193, 268, 301, 311, 403, 456, 518, 603,
       644, 692, 734, 780, 863])

In [329]:
np.cumsum (b,axis=0)


array([[ 20,  55,  31,  24,  14,  49],
       [ 95,  88,  41, 116,  67, 111],
       [180, 129,  89, 158, 113, 194]])

In [330]:
np.cumsum (b,axis=1)


array([[ 20,  75, 106, 130, 144, 193],
       [ 75, 108, 118, 210, 263, 325],
       [ 85, 126, 174, 216, 262, 345]])

# np.percentile 


In [331]:
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [333]:
print(np.percentile (a,100) )    # max


90.0


In [334]:
print(np.percentile (a,0) )    # min


8.0


In [335]:
print(np.percentile (a,50) )    # median


42.0


In [337]:
print(np.median(a))

42.0


# np.isin 


In [338]:
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [339]:
items=[10,20,30,40,50,60,70]
np.isin(a,items)                 # 10 and last 40 is there that's why True

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [340]:
a[np.isin(a,items)] 


array([10, 40], dtype=int32)

In [341]:
# np.flip       - reverse the order  

In [342]:
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [344]:
np.flip(a)

array([40, 42,  8, 52, 65, 62, 14, 43, 23,  9, 78, 61, 26, 10, 90],
      dtype=int32)

In [345]:
b

array([[20, 55, 31, 24, 14, 49],
       [75, 33, 10, 92, 53, 62],
       [85, 41, 48, 42, 46, 83]], dtype=int32)

In [346]:
np.flip(b)

array([[83, 46, 42, 48, 41, 85],
       [62, 53, 92, 10, 33, 75],
       [49, 14, 24, 31, 55, 20]], dtype=int32)

In [347]:
np.flip(b,axis=0)

array([[85, 41, 48, 42, 46, 83],
       [75, 33, 10, 92, 53, 62],
       [20, 55, 31, 24, 14, 49]], dtype=int32)

In [348]:
np.flip(b,axis=1)

array([[49, 14, 24, 31, 55, 20],
       [62, 53, 92, 10, 33, 75],
       [83, 46, 42, 48, 41, 85]], dtype=int32)

# np.put 


In [349]:
# specific elem index replace with given value

In [350]:
a

array([90, 10, 26, 61, 78,  9, 23, 43, 14, 62, 65, 52,  8, 42, 40],
      dtype=int32)

In [356]:
np.put(a,[0,1],[110,200])      # [index],[value]

In [357]:
a

array([110, 200,  26,  61,  78,   9,  23,  43,  14,  62,  65,  52,   8,
        42,  40], dtype=int32)

# np.delete

In [358]:
a

array([110, 200,  26,  61,  78,   9,  23,  43,  14,  62,  65,  52,   8,
        42,  40], dtype=int32)

In [359]:
np.delete(a,0)                 # index no. value delete

array([200,  26,  61,  78,   9,  23,  43,  14,  62,  65,  52,   8,  42,
        40], dtype=int32)

# np.clip - limit the value


In [362]:
a

array([110, 200,  26,  61,  78,   9,  23,  43,  14,  62,  65,  52,   8,
        42,  40], dtype=int32)

In [364]:
np.clip(a,a_min=15,a_max=50)        # 15 & below 15 replace with 15
                                    # 50 & above 50 replace with 50

array([50, 50, 26, 50, 50, 15, 23, 43, 15, 50, 50, 50, 15, 42, 40],
      dtype=int32)

# np.swapaxes    

In [366]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [367]:
np.swapaxes(arr,0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])