# Numpy

In [3]:
import numpy as np

In [5]:
np.__version__

'2.3.5'

In [2]:
list=[1,2,3,4,5,6]
list

[1, 2, 3, 4, 5, 6]

In [8]:
arr=np.array(list)
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
print(type(list))
print(type(arr))      

<class 'list'>
<class 'numpy.ndarray'>


# arange

In [11]:
np.arange(4)      # arange work as range  

array([0, 1, 2, 3])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(10,20,3,4)    # 3 arg allow

TypeError: Cannot interpret '4' as a data type

In [17]:
np.arange(20,10)     #  1st arg should be always small

NameError: name 'nparange' is not defined

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [22]:
# zeros   - bydefault in flaot

In [23]:
np.zeros(4)     # 1d array

array([0., 0., 0., 0.])

In [25]:
np.zeros([2,2])     # 2d array

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [29]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros([10,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# ones  - bydefault in float

In [34]:
np.ones([5])

array([1., 1., 1., 1., 1.])

In [36]:
np.ones([1,10],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [37]:
np.two(5)        # their is fun name such as two

AttributeError: module 'numpy' has no attribute 'two'

# random

In [38]:
np.random.rand(5)        # it gives any random values 5 times

array([0.29803454, 0.86990354, 0.96451306, 0.36980474, 0.39194368])

In [42]:
np.random.rand(2,5)         # 2*5 matrix

array([[0.40503659, 0.28784049, 0.8574148 , 0.70094152, 0.8967477 ],
       [0.78552245, 0.90242915, 0.45465533, 0.05860523, 0.89520982]])

In [45]:
np.random.rand(1,4,2)   # 1 block , 4 rows , 2 column

array([[[0.17381968, 0.55685514],
        [0.80586716, 0.94250399],
        [0.15352992, 0.24749226],
        [0.7150395 , 0.6101928 ]]])

In [46]:
np.random.randint(6)      # randon value 0 to 5

3

In [47]:
np.random.randint(10,20)    # 10 to 19

13

In [48]:
np.random.randint(1,10,4)       # 4 means ,random 4 values

array([4, 3, 2, 9], dtype=int32)

In [49]:
print(np.random.randint(1,10,4))

[1 9 9 6]


In [50]:
np.random.randint(1,10,(3,4))     # 3*4 matrix ,1 to 9

array([[4, 1, 1, 8],
       [4, 1, 7, 1],
       [9, 1, 9, 5]], dtype=int32)

In [51]:
np.random.randint(10,20,(2,2))

array([[15, 19],
       [10, 10]], dtype=int32)

In [56]:
m=np.random.randint(10,30,(3,2))
m

array([[25, 21],
       [20, 26],
       [19, 24]], dtype=int32)

In [57]:
print(m)     # print = remove , in matrix

[[25 21]
 [20 26]
 [19 24]]


In [58]:
m[0]     # 0th row

array([25, 21], dtype=int32)

In [59]:
print(m[0])

[25 21]


In [60]:
print(m[-2])

[20 26]


In [61]:
print(m[-1])

[19 24]


In [62]:
print(m[2,-1])     # 2nd row , -1 column

24


In [63]:
print(m[-2,-1])

26
